### ISSUE TITLE
examples in README show non-english results

### ISSUE THREAD

**Issue by mtmail** [WebGents/open_street_map#1]
When calling the Nominatim API programmatically the results (place names) will default to english. One would have to set an `accept-language` header or URL parameter in the requests to change that.

The README lists 
```
      "country":"Великобритания",
```
which must have been copy&pasted from browser output.

https://github.com/openstreetmap/Nominatim/issues/1104 has another example explaining the URL parameter.

**Comment by kortirso** [comment]
Added accept_language parameter
https://github.com/WebGents/open_street_map/commit/10697b3a11ffe87e17b42456649d5021ee94d32b
