### ISSUE TITLE
Library doesn't follow nominatim.osm.org usage policy

### ISSUE THREAD

**Issue by mtmail** [WebGents/open_street_map#2]
https://operations.osmfoundation.org/policies/nominatim/

The library should
1. allow overwriting the host name for users who have their own Nominatim installation (or use a mirror)
1. allow setting the `email` parameter, even better if enforced
1. allow overwriting the user agent string

Optionally
* Enforce one request per second
* Add disclaimer to the README

The default user agent string is too generic. If one library user overuses the nominatim.osm.org server all users with the same string are at risk to get blocked. It's not ready for production use, e.g. bulk geocoding, because the underlying service (nominatim.osm.org) doesn't allow those use cases.

**Comment by kortirso** [comment]
1. Added hostname parameter for overwriting
2. Added email parameter
3. Added user_agent parameter
4. Added 1 second request timeout
5. Modified readme

**Comment by mtmail** [comment]
That's awesome!
