### ISSUE TITLE
This is not the timeout

### ISSUE THREAD

**Issue by kvokka** [WebGents/open_street_map#4]
Current behaviour on this line 

https://github.com/WebGents/open_street_map/blob/37be690e860e87b0b4dfa9d0aa982e4721704626/lib/open_street_map/client/request.rb#L10

mislead the naming. 
It looks like it should get the result, and return it when response came back. But not it will always return something in 1+ second.

It is not a timeout, it is wrong logic.

**Comment by kortirso** [comment]
Timeout is removed, users must define a timeout between requests by self
